require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FightsController do

  # This should return the minimal set of attributes required to create a valid
  # Fight. As you add validations to Fight, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FightsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all fights as @fights" do
      fight = Fight.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fights).should eq([fight])
    end
  end

  describe "GET show" do
    it "assigns the requested fight as @fight" do
      fight = Fight.create! valid_attributes
      get :show, {:id => fight.to_param}, valid_session
      assigns(:fight).should eq(fight)
    end
  end

  describe "GET new" do
    it "assigns a new fight as @fight" do
      get :new, {}, valid_session
      assigns(:fight).should be_a_new(Fight)
    end
  end

  describe "GET edit" do
    it "assigns the requested fight as @fight" do
      fight = Fight.create! valid_attributes
      get :edit, {:id => fight.to_param}, valid_session
      assigns(:fight).should eq(fight)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fight" do
        expect {
          post :create, {:fight => valid_attributes}, valid_session
        }.to change(Fight, :count).by(1)
      end

      it "assigns a newly created fight as @fight" do
        post :create, {:fight => valid_attributes}, valid_session
        assigns(:fight).should be_a(Fight)
        assigns(:fight).should be_persisted
      end

      it "redirects to the created fight" do
        post :create, {:fight => valid_attributes}, valid_session
        response.should redirect_to(Fight.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fight as @fight" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fight.any_instance.stub(:save).and_return(false)
        post :create, {:fight => {}}, valid_session
        assigns(:fight).should be_a_new(Fight)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fight.any_instance.stub(:save).and_return(false)
        post :create, {:fight => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fight" do
        fight = Fight.create! valid_attributes
        # Assuming there are no other fights in the database, this
        # specifies that the Fight created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Fight.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => fight.to_param, :fight => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested fight as @fight" do
        fight = Fight.create! valid_attributes
        put :update, {:id => fight.to_param, :fight => valid_attributes}, valid_session
        assigns(:fight).should eq(fight)
      end

      it "redirects to the fight" do
        fight = Fight.create! valid_attributes
        put :update, {:id => fight.to_param, :fight => valid_attributes}, valid_session
        response.should redirect_to(fight)
      end
    end

    describe "with invalid params" do
      it "assigns the fight as @fight" do
        fight = Fight.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fight.any_instance.stub(:save).and_return(false)
        put :update, {:id => fight.to_param, :fight => {}}, valid_session
        assigns(:fight).should eq(fight)
      end

      it "re-renders the 'edit' template" do
        fight = Fight.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fight.any_instance.stub(:save).and_return(false)
        put :update, {:id => fight.to_param, :fight => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fight" do
      fight = Fight.create! valid_attributes
      expect {
        delete :destroy, {:id => fight.to_param}, valid_session
      }.to change(Fight, :count).by(-1)
    end

    it "redirects to the fights list" do
      fight = Fight.create! valid_attributes
      delete :destroy, {:id => fight.to_param}, valid_session
      response.should redirect_to(fights_url)
    end
  end

end
